/**
* Finflux-Authentication
* Finflux Authentication APIs
*
* The version of the OpenAPI document: Authentication-1.0
* Contact: develop@finflux.co
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package co.finflux.openapi.auth


import com.squareup.moshi.Json

/**
 * 
 * @param accessToken 
 * @param tokenType 
 * @param refreshToken 
 * @param expiresIn 
 * @param scope 
 */

data class AccessTokenResponse (
    @Json(name = "access_token")
    val accessToken: kotlin.String? = null,
    @Json(name = "token_type")
    val tokenType: kotlin.String? = null,
    @Json(name = "refresh_token")
    val refreshToken: kotlin.String? = null,
    @Json(name = "expires_in")
    val expiresIn: kotlin.Long? = null,
    @Json(name = "scope")
    val scope: kotlin.String? = null
)

