/**
* Finflux
* Finflux Authentication APIs
*
* The version of the OpenAPI document: Authentication-1.0
* Contact: develop@finflux.co
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * To fetch a access token by refresh token
 * @param clientId Client-Id provided by finflux
 * @param grantType 
 * @param refreshToken Refresh token that is generated at the time of token generation
 */

data class RefreshTokenPayload (
    /* Client-Id provided by finflux */
    @Json(name = "client_id")
    val clientId: kotlin.String,
    @Json(name = "grant_type")
    val grantType: kotlin.String,
    /* Refresh token that is generated at the time of token generation */
    @Json(name = "refresh_token")
    val refreshToken: kotlin.String
)

